In [1]:
import numpy as np

##### Create two matrices to then solve using numpy function.

###### The algorithm uses LU decomposition to determine the solutions of x. - ??

In [2]:
solve_A = np.array([[1, 3, -1], [2, -1, 1], [-1, 1, -2]])
solve_y = np.array([[-6], [1], [-4]])

##### Compute the solution and then print it out.

In [4]:
print(f"We want to solve: \n{solve_A}\n with the vector \n{solve_y}\n ")

x = np.linalg.solve(solve_A, solve_y)
print(f"The solution is: \n{x}\n ")

We want to solve: 
[[ 1  3 -1]
 [ 2 -1  1]
 [-1  1 -2]]
 with the vector 
[[-6]
 [ 1]
 [-4]]
 
The solution is: 
[[-1.]
 [-1.]
 [ 2.]]
 


##### This result matches the one I did by hand using Gaussian Elimination. Now, let's go ahead and compute various matrix operations.

In [5]:
A = np.array([[1, 0, 7], [8, 4, 1], [0, 1, 0]])
B = np.array([[-1, 2, 3], [0, 1, -1], [3, 1, 4]])
C = np.array([[1], [2], [3]])

In [6]:
print(f"Matrix A is: \n{A}\n ")
print(f"Matrix B is: \n{B}\n ")

Matrix A is: 
[[1 0 7]
 [8 4 1]
 [0 1 0]]
 
Matrix B is: 
[[-1  2  3]
 [ 0  1 -1]
 [ 3  1  4]]
 


##### We'll use various numpy functions to determine the product and determinant as well as other operations.

In [7]:
print(f"Product of Matrix AB: \n{np.dot(A, B)}\n ")

print(f"The determinant of A is: \n{np.linalg.det(A)}\n and the determinant of B is: \n{np.linalg.det(B)}\n ")

Product of Matrix AB: 
[[20  9 31]
 [-5 21 24]
 [ 0  1 -1]]
 
The determinant of A is: 
54.999999999999964
 and the determinant of B is: 
-20.000000000000007
 


##### Let's see if the inverses exist for Matrix A and B.

In [8]:
print(f"Inverse of A: \n{np.linalg.inv(A)}\n Inverse of B: \n{np.linalg.inv(B)}")

Inverse of A: 
[[-0.01818182  0.12727273 -0.50909091]
 [ 0.          0.          1.        ]
 [ 0.14545455 -0.01818182  0.07272727]]
 Inverse of B: 
[[-0.25  0.25  0.25]
 [ 0.15  0.65  0.05]
 [ 0.15 -0.35  0.05]]


##### Great! We can see that the inverses do exist. Let's determine the rank of each matrix.

###### The rank of a matrix will tell us about whether a vector is linearly independent or dependent.

In [9]:
print(f"Rank of A is: \n{np.linalg.matrix_rank(A)}\n Rank of B is: \n{np.linalg.matrix_rank(B)}\n ")

Rank of A is: 
3
 Rank of B is: 
3
 


##### Now, we need to figure out if the vector y is a linear combination of the columns of matrix A.

###### We can do this by checking the rank of an augmented matrix of A and y (which is C). 

In [10]:
if np.linalg.matrix_rank(np.concatenate((A, C), axis=1)) == np.linalg.matrix_rank(A) + 1:
    print(f"The system of equations is consistent and has a unique solution.")
else:
    print(f"The system of equations is inconsistent and has no solution.")

The system of equations is inconsistent and has no solution.


##### Thus, we have our answer that there is no solution with the addition of our vector y.